<p>
	<strong><a href=" https://sites.google.com/a/hillsideclub.org/hillsideclub/programs/last-friday-ladies-lunch" target="_parent">Last Friday Ladies Lunch — Noon to 1:30 PM</a></strong>
	<br />Friday, May 30, 2014
	<br />12:00 - 13:30 PST
</p><p>
	<strong><a href=" https://sites.google.com/a/hillsideclub.org/hillsideclub/the-simple-home/ruskin-conference---2014" target="_parent">Hillside Club Roundtable - Helping in the Work of Creation: John Ruskin and William Morris Today</a></strong>
	<br />Saturday, May 31, 2014
	<br />09:00 - 17:00 PST
</p><p>
	<strong><a href=" http://www.pocketopera.org/2014/PO-2014-Fishers.html" target="_parent">Pocket Opera - The Pearl Fishers - Bizet - 2:00pm</a></strong>
	<br />Sunday, June 01, 2014
	<br />14:00 - 16:30 PST
</p><p>
	<strong><a href="  https://sites.google.com/a/hillsideclub.org/hillsideclub/book-lust-salon-1" target="_parent">Hillside Club Book Group II in the Green Room, 7:00 pm</a></strong>
	<br />Tuesday, June 10, 2014
	<br />19:00 - 21:00 PST
</p><p>
	<strong><a href=" https://sites.google.com/a/hillsideclub.org/hillsideclub/hsc-potluck" target="_parent">Pot Luck</a></strong>
	<br />Saturday, June 21, 2014
	<br />18:30 - 20:30 PST
</p><p>
	<strong><a href="  https://sites.google.com/a/hillsideclub.org/hillsideclub/book-lust-salon-1" target="_parent">Hillside Book Group in the Green Room, 7:30 pm</a></strong>
	<br />Tuesday, June 24, 2014
	<br />19:30 - 21:00 PST
</p><p>
	<strong><a href=" https://sites.google.com/a/hillsideclub.org/hillsideclub/programs/last-friday-ladies-lunch" target="_parent">Last Friday Ladies Lunch — Noon to 1:30 PM</a></strong>
	<br />Friday, June 27, 2014
	<br />12:00 - 13:30 PST
</p><p>
	<strong><a href="  https://sites.google.com/a/hillsideclub.org/hillsideclub/book-lust-salon-1" target="_parent">Hillside Club Book Group II in the Green Room, 7:00 pm</a></strong>
	<br />Tuesday, July 08, 2014
	<br />19:00 - 21:00 PST
</p><p>
	<strong><a href="  https://sites.google.com/a/hillsideclub.org/hillsideclub/book-lust-salon-1" target="_parent">Hillside Book Group in the Green Room, 7:30 pm</a></strong>
	<br />Tuesday, July 22, 2014
	<br />19:30 - 21:00 PST
</p><p>
	<strong><a href="  https://sites.google.com/a/hillsideclub.org/hillsideclub/the-simple-home" target="_parent">Hillside Club Round Table</a></strong>
	<br />Wednesday, July 23, 2014
	<br />19:30 - 21:00 PST
</p>